### ISSUE TITLE
Feedback - HTML Widgets

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/blog-guidance#94] opened 2020-02-27 22:44 UTC
For the [2.3.7 Don’t use html widgets](https://blogguide.ropensci.org/technical.html#dont-use-html-widgets) section, consider

1) moving this to be a bullet in the Style Guide (it's not a how to, so perhaps doesn't belong in the code snippets section)
2) add the option of using a screenshot of an HTML widget, if people want to showcase that kind of thing

**Comment by maelle** [comment] 2020-03-02 09:00
If people add a screenshot they could use the `link` option of the Hugo shortcode to direct readers to an online version of the widget.

**Comment by stefaniebutland** [comment] 2020-03-04 20:09
addressed in https://github.com/ropensci-org/blog-guidance/pull/100

**Comment by maelle** [comment] 2020-03-05 09:21
In my opinion it'd be easier to add the issue number in the first comment of the PR. This way in the first comment of the PR there would be `Addresses #100 #96` etc and when merging it I could copy paste the issue numbers and write `fix #100 fix #96` in the commit message. :wink:

**Comment by maelle** [comment] 2020-03-05 10:12
(I've done that in PR 100)

**Closed** 2020-03-05 10:19 UTC

**Comment by maelle** [comment] 2020-03-11 07:53
@stefaniebutland My advice on linking issue was slightly outdated cf https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue The best would be for the description of the PR to include `fix #100 fix #96` and not `Addresses #100 #96` (alternatively, see the GitHub docs on how to link issues manually). This way the issue is linked to the PR and once the PR is merged the issue is closed.
